---

- name: Harden sshd
  template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
  notify: Restart sshd
  when: enable_sshd

- name: Copy fail2ban jail.local
  template:
    src: templates/jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  notify: Restart fail2ban
  when: enable_fail2ban
