---

- name: Create systemd-tmpfiles
  command: /usr/bin/systemd-tmpfiles --prefix=/sys --create

- name: Unload iwlmvm
  modprobe:
    name: iwlmvm
    state: absent
  notify: Load iwlmvm

- name: Load iwlmvm
  modprobe:
    name: iwlmvm
    state: present

- name: Restart sshd
  service:
    name: sshd
    state: restarted

- name: Restart fail2ban
  service:
    name: fail2ban
    state: restarted
